-- Flappy Void schema for Supabase

create table if not exists profiles (
  id uuid primary key references auth.users on delete cascade,
  username text not null unique,
  avatar_url text,
  best_score integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  score integer not null,
  created_at timestamptz not null default now()
);

create index if not exists scores_user_id_score_idx on scores (user_id, score desc);

create or replace view leaderboard as
select
  p.id as user_id,
  p.username,
  p.best_score,
  p.avatar_url,
  rank() over (order by p.best_score desc, p.created_at asc) as rank
from profiles p;

create or replace function get_user_rank(uid uuid)
returns integer
language sql
stable
as $$
  select rank from leaderboard where user_id = uid;
$$;

alter table profiles enable row level security;
alter table scores enable row level security;

drop policy if exists "Profiles viewable by everyone" on profiles;
drop policy if exists "Users can insert own profile" on profiles;
drop policy if exists "Users can update own profile" on profiles;
drop policy if exists "Users can insert own scores" on scores;
drop policy if exists "Users can read own scores" on scores;

create policy "Profiles viewable by everyone"
  on profiles for select
  using (true);

create policy "Users can insert own profile"
  on profiles for insert
  with check (auth.uid() = id);

create policy "Users can update own profile"
  on profiles for update
  using (auth.uid() = id);

create policy "Users can insert own scores"
  on scores for insert
  with check (auth.uid() = user_id);

create policy "Users can read own scores"
  on scores for select
  using (auth.uid() = user_id);
